#include <stdlib.h>
#include <stdio.h>
#include "mod_lista.h"

// ESTRUTURA PARA JUNTAR OS NÓS DA LISTA: INFO E PONTEIRO


// FUNCAO CRIAR LISTA, ALOCA MEMORIA PARA UMA LISTA


// FUNCAO PARA INSERIR ELEMENTOS NA LISTA, NO INICIO


// FUNCAO PARA IMPRIMIR OS ELEMENTOS DA LISTA


// FUNCAO PARA VERIFICAR SE A LISTA ESTA VAZIA


// FUNCAO PARA PERCORRER A LISTA E BUSCAR ELEMENTO INSERIDO


// FUNCAO PARA LIBERAR A MEMORIA DO NÓ 


// FUNCAO PARA ELEMENTOS ORDENADOS


